version: 2.1

executors:
  openjdk-node-heroku:
    docker:
      - image: guilgaly/openjdk-mill-node-heroku:11.0.2-0.3.6-stretch
    working_directory: /tmp/cowsay-online
    environment:
      JVM_OPTS: -Xmx2g
      TERM: dumb

jobs:
  build-deploy:
    executor: openjdk-node-heroku
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-coursier-{{ checksum "dependencies.sc" }}
            - v1-coursier-
      - run: ./.circleci/build.sh
      - run: ./.circleci/deploy.sh
      - save_cache:
          key: v1-coursier-{{ checksum "dependencies.sc" }}
          paths:
            - ~/.cache/coursier

workflows:
  version: 2
  build:
    jobs:
      - build-deploy:
          name: "Build & deploy"
